# Generated by Django 5.0.6 on 2024-06-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_can_add_customers',
            field=models.BooleanField(default=False, verbose_name='is_can_add_customers'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_can_add_workers',
            field=models.BooleanField(default=False, verbose_name='is_can_add_workers'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_can_create_tasks',
            field=models.BooleanField(default=False, verbose_name='is_can_create_tasks'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_have_access_to_tasks',
            field=models.BooleanField(default=False, verbose_name='is_have_access_to_tasks'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_have_access_to_workers',
            field=models.BooleanField(default=False, verbose_name='is_have_access_to_workers'),
        ),
    ]
