# Generated by Django 5.0.6 on 2024-06-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_customer_alter_task_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'to_do'), ('in_progress', 'in_progress'), ('completed', 'completed')], default='to_do', max_length=11, verbose_name='status'),
        ),
    ]
