# Generated by Django 5.0.6 on 2024-06-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='task',
            name='report',
            field=models.TextField(blank=True, null=True, verbose_name='report'),
        ),
    ]
